spring:
  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
